# Generated by Django 2.2.24 on 2023-06-07 10:29

from django.db import migrations
from property.models import Flat


def automatically_fill_new_building(apps, schema_editor):
    Flat.objects.filter(construction_year__gte=2015).update(new_building=True)
    Flat.objects.exclude(construction_year__gte=2015).update(new_building=False)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(automatically_fill_new_building)
    ]
