# Generated by Django 2.2.24 on 2023-06-07 14:07

from django.db import migrations


def copy_flat_to_owner(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.all():
        owner = Owner(
            owner=flat.owner,
            owners_phonenumber=flat.owners_phonenumber,
        )
        if flat.owner_pure_phone is not None:
            owner.owner_pure_phone = flat.owner_pure_phone
        owner.save()


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0009_owner'),
    ]

    operations = [
        migrations.RunPython(copy_flat_to_owner)
    ]
