# Generated by Django 2.2.24 on 2023-06-08 09:05

from django.db import migrations


def copy_flat_to_owner(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        if flat.owner_pure_phone is not None:
            owner, created = Owner.objects.get_or_create(owner=flat.owner, owners_phonenumber=flat.owners_phonenumber,
                                                         owner_pure_phone=flat.owner_pure_phone)
            owner.owned_apartments.set([flat])


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0011_auto_20230608_1204'),
    ]

    operations = [
        migrations.RunPython(copy_flat_to_owner)
    ]
