# Generated by Django 2.2.24 on 2023-06-09 06:52

from django.db import migrations


def copy_flat_to_owner(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Flat = apps.get_model('property', 'Flat')

    all_flats = Flat.objects.all()
    if all_flats.exists():
        for flat in all_flats.iterator():
            if flat.owner_pure_phone is not None:
                owner, created = Owner.objects.get_or_create(owner=flat.owner, phone_number=flat.owners_phonenumber,
                                                             pure_phone=flat.owner_pure_phone)
                owner.apartments.set([flat])


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20230609_0951'),
    ]

    operations = [
        migrations.RunPython(copy_flat_to_owner)
    ]
